# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"\x94\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x04\x12\x15\n\rprev_log_term\x18\x04 \x01(\x04\x12\x15\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x04.Log\x12\x15\n\rleader_commit\x18\x06 \x01(\x04\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0f\n\x07success\x18\x02 \x01(\x08\"g\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x04\x12\x15\n\rlast_log_term\x18\x04 \x01(\x04\"9\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"3\n\x03Log\x12\r\n\x05index\x18\x01 \x01(\x04\x12\x0c\n\x04term\x18\x02 \x01(\x04\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\"\'\n\x14\x43lientRequestMessage\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"\\\n\x15\x43lientResponseMessage\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\x13\n\x0bleader_hint\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"\x80\x01\n\x16InstallSnapshotRequest\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x1b\n\x13last_included_index\x18\x03 \x01(\x04\x12\x1a\n\x12last_included_term\x18\x04 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\"\'\n\x17InstallSnapshotResponse\x12\x0c\n\x04term\x18\x01 \x01(\x04\x32\x8d\x02\n\x0bRaftService\x12>\n\rAppendEntries\x12\x15.AppendEntriesRequest\x1a\x16.AppendEntriesResponse\x12\x38\n\x0bRequestVote\x12\x13.RequestVoteRequest\x1a\x14.RequestVoteResponse\x12>\n\rClientRequest\x12\x15.ClientRequestMessage\x1a\x16.ClientResponseMessage\x12\x44\n\x0fInstallSnapshot\x12\x17.InstallSnapshotRequest\x1a\x18.InstallSnapshotResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPENDENTRIESREQUEST']._serialized_start=15
  _globals['_APPENDENTRIESREQUEST']._serialized_end=163
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=165
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=219
  _globals['_REQUESTVOTEREQUEST']._serialized_start=221
  _globals['_REQUESTVOTEREQUEST']._serialized_end=324
  _globals['_REQUESTVOTERESPONSE']._serialized_start=326
  _globals['_REQUESTVOTERESPONSE']._serialized_end=383
  _globals['_LOG']._serialized_start=385
  _globals['_LOG']._serialized_end=436
  _globals['_CLIENTREQUESTMESSAGE']._serialized_start=438
  _globals['_CLIENTREQUESTMESSAGE']._serialized_end=477
  _globals['_CLIENTRESPONSEMESSAGE']._serialized_start=479
  _globals['_CLIENTRESPONSEMESSAGE']._serialized_end=571
  _globals['_INSTALLSNAPSHOTREQUEST']._serialized_start=574
  _globals['_INSTALLSNAPSHOTREQUEST']._serialized_end=702
  _globals['_INSTALLSNAPSHOTRESPONSE']._serialized_start=704
  _globals['_INSTALLSNAPSHOTRESPONSE']._serialized_end=743
  _globals['_RAFTSERVICE']._serialized_start=746
  _globals['_RAFTSERVICE']._serialized_end=1015
# @@protoc_insertion_point(module_scope)
